tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "grep"
brew "htop"
brew "tmux"
brew "aquaproj/aqua/aqua"
brew "tree"

cask "font-hack-nerd-font"
cask "gitify"
cask "discord"
cask "docker"
